### ISSUE TITLE
Install osem

### ISSUE THREAD

**Issue by stephlocke** [lockedata/rcms#2]

**Comment by ZoeLocke** [comment]
Deploy to Heroku. Requires the following fields to be completed:

- CLOUDINARY_URL
- DATABASE_URL
- DEPLOY_TASKS
- LANG
- OSEM_DEVISE_SECRET_KEY
- OSEM_EMAIL_ADDRESS
- OSEM_HOSTNAME
- OSEM_NAME
- OSEM_SMTP_ADDRESS
- OSEM_SMTP_AUTHENTICATION
- OSEM_SMTP_DOMAIN
- OSEM_SMTP_PASSWORD
- OSEM_SMTP_PORT
- OSEM_SMTP_USERNAME
- RACK_ENV
- RAILS_ENV
- RAILS_SERVE_STATIC_FILES
- SECRET_KEY_BASE

These are ALL required fields!
